# ============================================================
# MindScan â€” docker-compose.yml
# ============================================================

version: "3.9"

services:

  mindscan-api:
    build: .
    container_name: mindscan_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./generated_reports:/app/generated_reports
    environment:
      MINDSCAN_REPORT_OUTPUT: "/app/generated_reports"
