version: "3.9"

services:

  mindscan_api:
    build: ..
    container_name: mindscan_api
    restart: always
    expose:
      - "8000"
    volumes:
      - ../generated_reports:/app/generated_reports
    environment:
      MINDSCAN_REPORT_OUTPUT: "/app/generated_reports"

  nginx:
    image: nginx:latest
    container_name: mindscan_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../web:/usr/share/nginx/html:ro
    depends_on:
      - mindscan_api
